Traceback (most recent call last):
  File "server.py", line 7, in <module>
    from gbk_database.config import config, Constants
  File "/home/chiro/gits/group-buying-killer/backend/gbk_database/config.py", line 149, in <module>
    config = Config()
  File "/home/chiro/gits/group-buying-killer/backend/gbk_database/config.py", line 119, in __init__
    self.load()
  File "/home/chiro/gits/group-buying-killer/backend/gbk_database/config.py", line 138, in load
    result = col.find_one({'version': {'$exists': True}}, {'_id': 0})
  File "/home/chiro/miniconda3/envs/gbk/lib/python3.8/site-packages/pymongo/collection.py", line 1319, in find_one
    for result in cursor.limit(-1):
  File "/home/chiro/miniconda3/envs/gbk/lib/python3.8/site-packages/pymongo/cursor.py", line 1207, in next
    if len(self.__data) or self._refresh():
  File "/home/chiro/miniconda3/envs/gbk/lib/python3.8/site-packages/pymongo/cursor.py", line 1124, in _refresh
    self.__send_message(q)
  File "/home/chiro/miniconda3/envs/gbk/lib/python3.8/site-packages/pymongo/cursor.py", line 999, in __send_message
    response = client._run_operation_with_response(
  File "/home/chiro/miniconda3/envs/gbk/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1368, in _run_operation_with_response
    return self._retryable_read(
  File "/home/chiro/miniconda3/envs/gbk/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1471, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/home/chiro/miniconda3/envs/gbk/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1360, in _cmd
    return server.run_operation_with_response(
  File "/home/chiro/miniconda3/envs/gbk/lib/python3.8/site-packages/pymongo/server.py", line 135, in run_operation_with_response
    _check_command_response(first, sock_info.max_wire_version)
  File "/home/chiro/miniconda3/envs/gbk/lib/python3.8/site-packages/pymongo/helpers.py", line 164, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: there are no users authenticated, full error: {'ok': 0.0, 'errmsg': 'there are no users authenticated', 'code': 13, 'codeName': 'Unauthorized'}
